// <auto-generated />
namespace ApiShort.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Make_FacilityLevel_AutoProperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Make_FacilityLevel_AutoProperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202109020909567_Make_FacilityLevel_AutoProperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
